### PR TITLE
MCPERSON-2430: update dealer private offer cta in MC heads up

### PR DESCRIPTION
**Pull request by batzlerg**
same changes to dealer email copy here: https://github.com/1stdibs/email-templates/pull/257

### CODE REVIEW

**Comment by batzlerg** [comment]
@brettjashford 
(this isn't a 1stdibs repo, so I can't assign the PR)

**Comment by brettjashford** [comment]
@antialias  now that we have 1stdibs/web-mc-admin how can we sync these? should i copy and push the contents of brettjashford/web-mc-admin to 1stdibs/web-mc-admin, delete this repo and fork off of 1stdibs?

**Comment by antialias** [comment]
You shouldn't have to manually copy anything. Just add the 1stdibs fork as a remote and push your branches over to it.

**Comment by brettjashford** [comment]
1stdibs/web-mc-admin is just and empty repo, it's not a fork of mine. shouldn't mine be a fork from 1stdibs?

**Comment by antialias** [comment]
After you push your branches to the 1stdibs repo, you can delete your repo.
After that, you can fork off 1stdibs and the repo on your account will be private.

**Comment by antialias** [comment]
Before you do all that, be sure to merge the branch for this PR.

**Pull request merged**
